(function(window){
'use strict';
const SESSION_KEY='divergent_web_session_token_v1';
const USER_KEY='divergent_web_session_user';
const ACCESS_API='https://neauzvqroaszvqffahkv.functions.supabase.co/menu-access-api';
const LOGIN_API='https://neauzvqroaszvqffahkv.functions.supabase.co/web-fallback-auth';
const EMPTY={qc:false,claim:false,claim_pending:false,search:false,payroll:false,staff_expenses:false,user_management:false,invoice:false,billing:false,pnl:false};
let state={status:'idle',user:null,access:{...EMPTY},confirmed:false,error:''};
function token(){try{return localStorage.getItem(SESSION_KEY)||''}catch(_){return''}}
function normalize(raw){raw=raw||{};return{qc:!!raw.qc,claim:!!raw.claim,claim_pending:!!raw.claim_pending,search:!!raw.search,payroll:!!(raw.payroll||raw.staff_payroll),staff_expenses:!!(raw.staff_expenses||raw.staff_expense),user_management:!!raw.user_management,invoice:!!raw.invoice,billing:!!raw.billing,pnl:!!raw.pnl}}
function getState(){return{status:state.status,user:state.user?{...state.user}:null,access:{...state.access},confirmed:state.confirmed,error:state.error}}
function setState(user,access){state={status:'ready',user:user||null,access:normalize(access),confirmed:true,error:''};window.dispatchEvent(new CustomEvent('divergent:v2-auth',{detail:getState()}));return getState()}
function clear(){try{localStorage.removeItem(SESSION_KEY);localStorage.removeItem(USER_KEY)}catch(_){}state={status:'idle',user:null,access:{...EMPTY},confirmed:false,error:'AUTH_REQUIRED'};window.dispatchEvent(new CustomEvent('divergent:v2-auth',{detail:getState()}));return getState()}
async function refresh(){const t=token();if(!t)return clear();state.status='loading';try{const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),8000);let r;try{r=await fetch(ACCESS_API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:'{}',signal:ctl.signal})}finally{clearTimeout(timer)}const j=await r.json().catch(()=>({}));if(!r.ok||!j.access){if(['AUTH_INVALID','AUTH_REQUIRED'].includes(j.error))clear();else state={status:'error',user:null,access:{...EMPTY},confirmed:false,error:j.error||'ACCESS_FAILED'};return getState()}return setState(j.user,j.access)}catch(e){state={status:'error',user:null,access:{...EMPTY},confirmed:false,error:e&&e.name==='AbortError'?'TIMEOUT':'ACCESS_FAILED'};return getState()}}
async function login(username,password){username=String(username||'').trim();password=String(password||'');if(!username||!password)throw new Error('กรอก Username และ Password ให้ครบ');const r=await fetch(LOGIN_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'login',username,password})});const text=await r.text();let j={};try{j=text?JSON.parse(text):{}}catch(_){j={}}if(!r.ok){const map={INVALID_CREDENTIALS:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',USER_DISABLED:'บัญชีถูกระงับ',USER_EXPIRED:'บัญชีหมดอายุ',CREDENTIALS_REQUIRED:'กรอก Username และ Password ให้ครบ'};throw new Error(map[j.error]||j.detail||j.error||('HTTP '+r.status))}if(!j.session_token)throw new Error('ไม่พบ Session จากระบบ');localStorage.setItem(SESSION_KEY,j.session_token);localStorage.setItem(USER_KEY,JSON.stringify(j.user||{}));if(j.access)return setState(j.user,j.access);return refresh()}
async function logout(){const t=token();try{if(t)await fetch(LOGIN_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout',session_token:t})})}catch(_){}return clear()}
window.DivergentV2Auth=Object.freeze({refresh,login,logout,getState,can:function(k){return!!(state.confirmed&&state.access[k])},token});
})(window);