(function(){
'use strict';
const API='https://neauzvqroaszvqffahkv.functions.supabase.co/qc-api';
const BATCH_API='https://neauzvqroaszvqffahkv.functions.supabase.co/qc-batch-data';
const SITES=[
['PHUTTHAISONG','การไฟฟ้าส่วนภูมิภาคสาขาพุทไธสง'],['NONGSONGHONG','การไฟฟ้าส่วนภูมิภาคสาขาหนองสองห้อง'],['BUAYAI','การไฟฟ้าส่วนภูมิภาคอำเภอบัวใหญ่'],['PRATHAI','การไฟฟ้าส่วนภูมิภาคอำเภอประทาย'],['CHUMPHUANG','การไฟฟ้าส่วนภูมิภาคสาขาชุมพวง'],['CHATTURAT','การไฟฟ้าส่วนภูมิภาคสาขาจัตุรัส'],['BANFANG','การไฟฟ้าส่วนภูมิภาคอำเภอบ้านฝาง'],['KANTHARALAK','การไฟฟ้าส่วนภูมิภาคสาขากันทรลักษ์'],['KAENGKHRO','การไฟฟ้าส่วนภูมิภาคสาขาแก้งคร้อ'],['KOSUM','การไฟฟ้าส่วนภูมิภาคอำเภอโกสุมพิสัย']
];
let currentBatch=null, detailData=null, imageLimit=30;
function token(){return window.DivergentV2Auth&&window.DivergentV2Auth.token?window.DivergentV2Auth.token():''}
async function post(url,body){const t=token();if(!t)throw new Error('กรุณาเข้าสู่ระบบก่อน');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));return j}
function el(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(v){if(!v)return'-';const s=String(v);if(/^\d{8}$/.test(s))return s.slice(0,2)+'/'+s.slice(2,4)+'/'+s.slice(4);return s}
function mount(){const ws=document.querySelector('.workspace[data-workspace="qc"]');if(!ws||ws.dataset.qcv2Mounted==='1')return;ws.dataset.qcv2Mounted='1';ws.innerHTML=`<div class="qcv2"><div class="qcv2-head"><div><h2>ตรวจสอบงาน QC</h2><div id="qcv2State" class="qcv2-state">เลือกไซด์งานเพื่อดูชุดภาพล่าสุด</div></div><div class="qcv2-tools"><label>ไซด์งาน<select id="qcv2Site"><option value="">-- เลือกไซด์งาน --</option>${SITES.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label><button id="qcv2Load" type="button">โหลดรายการ</button></div></div><div id="qcv2Batches" class="qcv2-grid"><div class="qcv2-empty">ยังไม่ได้เลือกไซด์งาน</div></div><div id="qcv2Detail" class="qcv2-detail"><div class="qcv2-detail-head"><div><h3 id="qcv2Title">รายละเอียดชุดภาพ</h3><div id="qcv2Meta" class="qcv2-state"></div></div><div id="qcv2Summary" class="qcv2-summary"></div></div><div id="qcv2Images" class="qcv2-images"></div><button id="qcv2More" class="qcv2-more" type="button" hidden>แสดงเพิ่ม</button></div></div>`;
 el('qcv2Load').addEventListener('click',loadBatches);el('qcv2Site').addEventListener('change',()=>{if(el('qcv2Site').value)loadBatches()});el('qcv2More').addEventListener('click',()=>{imageLimit+=30;renderImages()});}
async function loadBatches(){const siteCode=el('qcv2Site').value;if(!siteCode)return;el('qcv2State').textContent='กำลังโหลดรายการ...';el('qcv2Batches').innerHTML='<div class="qcv2-empty">กำลังโหลด...</div>';el('qcv2Detail').classList.remove('open');try{const j=await post(API,{action:'batches',siteCode});const rows=j.batches||[];el('qcv2State').textContent='พบ '+rows.length+' ชุดภาพ';if(!rows.length){el('qcv2Batches').innerHTML='<div class="qcv2-empty">ไม่พบชุดภาพของไซด์นี้</div>';return}el('qcv2Batches').innerHTML=rows.map((r,i)=>`<button class="qcv2-batch" type="button" data-i="${i}"><b>${esc(r.site_name||r.site_code)}</b><span>วันที่งาน: ${esc(fmtDate(r.raw_date))}</span><span>ภาพ: ${Number(r.image_count||0).toLocaleString()} รูป · CA: ${Number(r.ca_count||0).toLocaleString()} ราย</span><span>สถานะ: ${esc(r.status||'-')}</span></button>`).join('');el('qcv2Batches').querySelectorAll('[data-i]').forEach(b=>b.addEventListener('click',()=>openBatch(rows[Number(b.dataset.i)])));}catch(e){el('qcv2State').textContent='โหลดไม่สำเร็จ';el('qcv2Batches').innerHTML='<div class="qcv2-error">'+esc(e.message)+'</div>'}}
async function openBatch(row){currentBatch=row;detailData=null;imageLimit=30;el('qcv2Detail').classList.add('open');el('qcv2Title').textContent=(row.site_name||row.site_code)+' · '+fmtDate(row.raw_date);el('qcv2Meta').textContent='Batch: '+row.batch_id;el('qcv2Summary').innerHTML='<span class="qcv2-pill">กำลังโหลดรายละเอียด...</span>';el('qcv2Images').innerHTML='<div class="qcv2-empty">กำลังโหลดรูปและพิกัด...</div>';el('qcv2More').hidden=true;try{detailData=await post(BATCH_API,{siteCode:row.site_code,rawDate:row.raw_date,batchId:row.batch_id});const coords=detailData.coordinates||[];const withNotice=coords.filter(x=>x.notice&&x.notice.actual_latitude!=null&&x.notice.actual_longitude!=null).length;const withMeter=coords.filter(x=>x.meter&&x.meter.latitude!=null&&x.meter.longitude!=null).length;const withRoute=coords.filter(x=>x.route&&Number.isFinite(Number(x.route.distance_m))).length;el('qcv2Summary').innerHTML=`<span class="qcv2-pill">ภาพ ${Number((detailData.images||[]).length).toLocaleString()}</span><span class="qcv2-pill">พิกัดใบเตือน ${withNotice}</span><span class="qcv2-pill">พิกัดมิเตอร์ ${withMeter}</span><span class="qcv2-pill">คำนวณระยะได้ ${withRoute}</span>`;renderImages();}catch(e){el('qcv2Summary').innerHTML='';el('qcv2Images').innerHTML='<div class="qcv2-error">'+esc(e.message)+'</div>'}}
async function signed(objectPath){try{const j=await post(API,{action:'signed-url',objectPath});return j.signedUrl||''}catch(_){return''}}
function coordMap(){const m={};for(const x of (detailData&&detailData.coordinates||[]))m[String(x.ca||'')]=x;return m}
function renderImages(){if(!detailData)return;const imgs=detailData.images||[],shown=imgs.slice(0,imageLimit),map=coordMap();el('qcv2Images').innerHTML=shown.map((x,i)=>{const c=map[String(x.ca||'')]||{},r=c.route||null;const dist=r&&Number.isFinite(Number(r.distance_m))?Number(r.distance_m):null;return `<div class="qcv2-img" data-img="${i}"><div class="qcv2-empty">กำลังโหลดรูป...</div><b>CA ${esc(x.ca||'-')}</b><small>${esc(x.name)}</small><small class="${dist!=null&&dist<=200?'qcv2-route-good':'qcv2-route-warn'}">${dist==null?'ระยะทาง: -':'ระยะทางถนน: '+Math.round(dist).toLocaleString()+' ม.'}</small></div>`}).join('');shown.forEach((x,i)=>{signed(x.objectPath).then(url=>{const box=el('qcv2Images').querySelector('[data-img="'+i+'"]');if(!box)return;const holder=box.firstElementChild;if(url){const im=document.createElement('img');im.loading='lazy';im.src=url;im.alt=x.name;holder.replaceWith(im)}else holder.textContent='โหลดรูปไม่ได้'})});el('qcv2More').hidden=imgs.length<=imageLimit;}
function boot(){mount();window.addEventListener('divergent:v2-auth',()=>{if(document.body.dataset.auth==='ready')mount()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();