(function(){
'use strict';

const API='https://neauzvqroaszvqffahkv.functions.supabase.co/qc-api';
const BATCH_API='https://neauzvqroaszvqffahkv.functions.supabase.co/qc-batch-data';
const LIFF_ID='2011407195-ZXPgFEKe';
const LIFF_SDK_URL='https://static.line-scdn.net/liff/edge/2/sdk.js';
const FALLBACK_SITES=[
['UDON','การไฟฟ้าส่วนภูมิภาคสาขาอุดรธานี'],['PHUWIANG','การไฟฟ้าส่วนภูมิภาคอำเภอภูเวียง'],['KRANUAN','การไฟฟ้าส่วนภูมิภาคสาขากระนวน'],['KOSUM','การไฟฟ้าส่วนภูมิภาคอำเภอโกสุมพิสัย'],['NONGSONGHONG','การไฟฟ้าส่วนภูมิภาคสาขาหนองสองห้อง'],['BANFANG','การไฟฟ้าส่วนภูมิภาคอำเภอบ้านฝาง'],['PHUKHIAO','การไฟฟ้าส่วนภูมิภาคสาขาภูเขียว'],['MANCHAKHIRI','การไฟฟ้าส่วนภูมิภาคสาขามัญจาคีรี'],['CHATTURAT','การไฟฟ้าส่วนภูมิภาคสาขาจัตุรัส'],['CHAIYAPHUM','การไฟฟ้าส่วนภูมิภาคจังหวัดชัยภูมิ'],['KAENGKHRO','การไฟฟ้าส่วนภูมิภาคสาขาแก้งคร้อ'],['NONGKI','การไฟฟ้าส่วนภูมิภาคสาขาหนองกี่'],['PRAKHONCHAI','การไฟฟ้าส่วนภูมิภาคสาขาประโคนชัย'],['KORAT2','การไฟฟ้าส่วนภูมิภาคสาขาเมืองนครราชสีมา2 (หัวทะเล)'],['PHUTTHAISONG','การไฟฟ้าส่วนภูมิภาคสาขาพุทไธสง'],['CHUMPHUANG','การไฟฟ้าส่วนภูมิภาคสาขาชุมพวง'],['SUNGNOEN','การไฟฟ้าส่วนภูมิภาคสาขาสูงเนิน'],['NONTHAI','การไฟฟ้าส่วนภูมิภาคสาขาโนนไทย'],['KANTHARALAK','การไฟฟ้าส่วนภูมิภาคสาขากันทรลักษ์'],['PRATHAI','การไฟฟ้าส่วนภูมิภาคอำเภอประทาย'],['BUAYAI','การไฟฟ้าส่วนภูมิภาคอำเภอบัวใหญ่'],['NONGBUNMAK','การไฟฟ้าส่วนภูมิภาคอำเภอหนองบุญมาก']];
let currentBatch=null,detailData=null,imageLimit=30,activeFilter='all',currentModalIndex=-1,modalRequestSeq=0,liffSdkPromise=null,liffReadyPromise=null;
const signedUrlCache=new Map();

function token(){return window.DivergentV2Auth&&window.DivergentV2Auth.token?window.DivergentV2Auth.token():''}
async function post(url,body){const t=token();if(!t)throw new Error('กรุณาเข้าสู่ระบบก่อน');const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));return j}
function el(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function fmtDate(v){if(!v)return'-';const s=String(v);return /^\d{8}$/.test(s)?s.slice(0,2)+'/'+s.slice(2,4)+'/'+s.slice(4):s}
function fmtCoord(v){const n=Number(v);return Number.isFinite(n)?n.toFixed(6):'-'}
function siteOptions(rows){return rows.map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join('')}

function mount(){const ws=document.querySelector('.workspace[data-workspace="qc"]');if(!ws||ws.dataset.qcv2Mounted==='1')return;ws.dataset.qcv2Mounted='1';ws.innerHTML=`<div class="qcv2"><div class="qcv2-head"><div><h2>ตรวจสอบงาน QC</h2><div id="qcv2State" class="qcv2-state">กำลังโหลดรายชื่อไซด์งาน...</div></div><div class="qcv2-tools"><label>ไซด์งาน<select id="qcv2Site"><option value="">-- กำลังโหลดไซด์งาน --</option></select></label><button id="qcv2Load" type="button">โหลดรายการ</button></div></div><div id="qcv2Batches" class="qcv2-grid"><div class="qcv2-empty">ยังไม่ได้เลือกไซด์งาน</div></div><div id="qcv2Detail" class="qcv2-detail"><div class="qcv2-detail-nav"><button id="qcv2BackBatches" type="button">← กลับไปรายการ Batch</button></div><div class="qcv2-detail-head"><div><h3 id="qcv2Title">รายละเอียดชุดภาพ</h3><div id="qcv2Meta" class="qcv2-state"></div></div><div id="qcv2Summary" class="qcv2-summary"></div></div><div id="qcv2Filter" class="qcv2-filter"></div><div id="qcv2Images" class="qcv2-images"></div><button id="qcv2More" class="qcv2-more" type="button" hidden>แสดงเพิ่ม</button></div></div>`;el('qcv2Load').addEventListener('click',loadBatches);el('qcv2Site').addEventListener('change',()=>{if(el('qcv2Site').value)loadBatches()});el('qcv2More').addEventListener('click',()=>{imageLimit+=30;renderImages()});el('qcv2BackBatches').addEventListener('click',showBatchList);el('qcv2Images').addEventListener('click',handleImageGridClick,true);ensureModal();loadSites()}

async function loadSites(){const s=el('qcv2Site');if(!s)return;const previous=s.value;try{const j=await post(API,{action:'sites'});let rows=(j.sites||[]).map(x=>[String(x.site_code||'').trim(),String(x.site_name||x.site_code||'').trim()]).filter(x=>x[0]);if(!rows.length)throw new Error('ไม่พบรายชื่อไซด์');s.innerHTML='<option value="">-- เลือกไซด์งาน --</option>'+siteOptions(rows);if(previous&&rows.some(x=>x[0]===previous))s.value=previous;el('qcv2State').textContent='พร้อมแล้ว · พบ '+rows.length+' ไซด์งาน'}catch(e){s.innerHTML='<option value="">-- เลือกไซด์งาน --</option>'+siteOptions(FALLBACK_SITES);if(previous&&FALLBACK_SITES.some(x=>x[0]===previous))s.value=previous;el('qcv2State').textContent='ใช้รายชื่อไซด์สำรอง · '+FALLBACK_SITES.length+' ไซด์'}}

function handleImageGridClick(e){const card=e.target&&e.target.closest?e.target.closest('.qcv2-img'):null;if(!card||!el('qcv2Images').contains(card))return;e.preventDefault();e.stopPropagation();openImageAt(Number(card.dataset.img))}
function visibleImages(){return filteredImages().slice(0,imageLimit)}
function openImageAt(index){const imgs=visibleImages();if(!imgs.length)return;const i=Math.max(0,Math.min(index,imgs.length-1));const x=imgs[i],map=coordMap();currentModalIndex=i;openImageDetail(x,map[String(x.ca||'')]||{},i,imgs.length)}
function moveModal(step){const imgs=visibleImages();if(!imgs.length)return;const n=currentModalIndex+step;if(n<0||n>=imgs.length)return;openImageAt(n)}
function closeModal(){const m=el('qcv2Modal');if(m)m.classList.remove('open');currentModalIndex=-1;modalRequestSeq++}
function showBatchList(){closeModal();currentBatch=null;detailData=null;el('qcv2Detail').classList.remove('open');el('qcv2Batches').classList.remove('qcv2-hidden');el('qcv2State').scrollIntoView({behavior:'smooth',block:'start'})}
function ensureModal(){if(el('qcv2Modal'))return;const m=document.createElement('div');m.id='qcv2Modal';m.className='qcv2-modal';m.setAttribute('role','dialog');m.setAttribute('aria-modal','true');m.innerHTML='<div class="qcv2-modal-card"><button id="qcv2ModalClose" class="qcv2-modal-close" type="button" aria-label="ปิด">×</button><div id="qcv2ModalBody"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)closeModal()});el('qcv2ModalClose').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(!m.classList.contains('open'))return;if(e.key==='Escape'){e.preventDefault();closeModal()}else if(e.key==='ArrowLeft'){e.preventDefault();moveModal(-1)}else if(e.key==='ArrowRight'){e.preventDefault();moveModal(1)}})}

async function loadBatches(){const siteCode=el('qcv2Site').value;if(!siteCode)return;closeModal();currentBatch=null;detailData=null;el('qcv2State').textContent='กำลังโหลดรายการ...';el('qcv2Batches').classList.remove('qcv2-hidden');el('qcv2Batches').innerHTML='<div class="qcv2-empty">กำลังโหลด...</div>';el('qcv2Detail').classList.remove('open');try{const j=await post(API,{action:'batches',siteCode}),rows=j.batches||[],totalImages=rows.reduce((s,r)=>s+Number(r.image_count||0),0),totalCa=rows.reduce((s,r)=>s+Number(r.ca_count||0),0);el('qcv2State').textContent='พบ '+rows.length+' ชุดภาพ · '+totalImages.toLocaleString()+' รูป · '+totalCa.toLocaleString()+' CA';if(!rows.length){el('qcv2Batches').innerHTML='<div class="qcv2-empty">ไม่พบชุดภาพของไซด์นี้</div>';return}el('qcv2Batches').innerHTML=rows.map((r,i)=>`<button class="qcv2-batch" type="button" data-i="${i}"><b>${esc(r.site_name||r.site_code)}</b><span>วันที่งาน: ${esc(fmtDate(r.raw_date))}</span><span>ภาพ: ${Number(r.image_count||0).toLocaleString()} รูป · CA: ${Number(r.ca_count||0).toLocaleString()} ราย</span><span>สถานะ: ${esc(r.status||'-')}</span><strong class="qcv2-openhint">กดเพื่อเปิดตรวจสอบ →</strong></button>`).join('');el('qcv2Batches').querySelectorAll('[data-i]').forEach(b=>b.addEventListener('click',()=>{el('qcv2Batches').querySelectorAll('.qcv2-batch').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');openBatch(rows[Number(b.dataset.i)])}))}catch(e){el('qcv2State').textContent='โหลดไม่สำเร็จ';el('qcv2Batches').innerHTML='<div class="qcv2-error">'+esc(e.message)+'</div>'}}

async function openBatch(row){closeModal();currentBatch=row;detailData=null;imageLimit=30;activeFilter='all';el('qcv2Batches').classList.add('qcv2-hidden');el('qcv2Detail').classList.add('open');el('qcv2Title').textContent=(row.site_name||row.site_code)+' · '+fmtDate(row.raw_date);el('qcv2Meta').textContent='Batch: '+row.batch_id;el('qcv2Summary').innerHTML='<span class="qcv2-pill">กำลังโหลดรายละเอียด...</span>';el('qcv2Filter').innerHTML='';el('qcv2Images').innerHTML='<div class="qcv2-empty">กำลังโหลดรูปและพิกัดใบแจ้งเตือน...</div>';el('qcv2More').hidden=true;requestAnimationFrame(()=>el('qcv2Detail').scrollIntoView({behavior:'smooth',block:'start'}));try{detailData=await post(BATCH_API,{siteCode:row.site_code,rawDate:row.raw_date,batchId:row.batch_id});renderSummary();renderFilter();renderImages()}catch(e){el('qcv2Summary').innerHTML='';el('qcv2Images').innerHTML='<div class="qcv2-error">'+esc(e.message)+'</div>'}}

function coordMap(){const m={};for(const x of (detailData&&detailData.coordinates||[]))m[String(x.ca||'')]=x;return m}
function hasNotice(c){const n=c&&c.notice||{};return n.actual_latitude!=null&&n.actual_longitude!=null&&Number.isFinite(Number(n.actual_latitude))&&Number.isFinite(Number(n.actual_longitude))}
function analyze(){const map=coordMap(),imgs=detailData&&detailData.images||[];let notice=0;for(const x of imgs)if(hasNotice(map[String(x.ca||'')]||{}))notice++;return{total:imgs.length,notice,missing:Math.max(0,imgs.length-notice)}}
function renderSummary(){const a=analyze();el('qcv2Summary').innerHTML=`<span class="qcv2-pill">ภาพ ${a.total.toLocaleString()}</span><span class="qcv2-pill qcv2-ok">มีพิกัดใบแจ้งเตือน ${a.notice.toLocaleString()}</span><span class="qcv2-pill">ไม่มีพิกัดใบแจ้งเตือน ${a.missing.toLocaleString()}</span>`}
function renderFilter(){const a=analyze(),filters=[['all','ทั้งหมด',a.total],['notice','มีพิกัดใบแจ้งเตือน',a.notice],['missing','ไม่มีพิกัดใบแจ้งเตือน',a.missing]];el('qcv2Filter').innerHTML=filters.map(x=>`<button type="button" data-filter="${x[0]}" class="${activeFilter===x[0]?'active':''}">${x[1]} <b>${x[2]}</b></button>`).join('');el('qcv2Filter').querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{closeModal();activeFilter=b.dataset.filter;imageLimit=30;renderFilter();renderImages()}))}
function filteredImages(){if(!detailData)return[];const map=coordMap(),imgs=detailData.images||[];if(activeFilter==='all')return imgs;if(activeFilter==='notice')return imgs.filter(x=>hasNotice(map[String(x.ca||'')]||{}));return imgs.filter(x=>!hasNotice(map[String(x.ca||'')]||{}))}
async function signed(objectPath){if(!objectPath)return'';if(signedUrlCache.has(objectPath))return signedUrlCache.get(objectPath);try{const j=await post(API,{action:'signed-url',objectPath}),url=j.signedUrl||'';if(url)signedUrlCache.set(objectPath,url);return url}catch(_){return''}}

function loadLineSdk(){if(window.liff)return Promise.resolve(window.liff);if(liffSdkPromise)return liffSdkPromise;liffSdkPromise=new Promise((resolve,reject)=>{let settled=false;const ok=()=>{if(settled)return;settled=true;window.liff?resolve(window.liff):reject(new Error('โหลด LINE SDK แล้วแต่ไม่พบ LIFF'))},bad=()=>{if(settled)return;settled=true;liffSdkPromise=null;reject(new Error('โหลด LINE SDK ไม่สำเร็จ'))},existing=Array.from(document.scripts).find(s=>String(s.src||'').includes('line-scdn.net/liff'));if(existing){if(window.liff){ok();return}existing.addEventListener('load',ok,{once:true});existing.addEventListener('error',bad,{once:true})}else{const s=document.createElement('script');s.src=LIFF_SDK_URL;s.async=true;s.addEventListener('load',ok,{once:true});s.addEventListener('error',bad,{once:true});document.head.appendChild(s)}setTimeout(()=>{if(!settled){if(window.liff)ok();else bad()}},12000)});return liffSdkPromise}
async function ensureLineReady(btn){await loadLineSdk();if(!liffReadyPromise)liffReadyPromise=liff.init({liffId:LIFF_ID,withLoginOnExternalBrowser:true}).catch(e=>{liffReadyPromise=null;throw e});await liffReadyPromise;if(!liff.isLoggedIn()){if(btn)btn.textContent='กำลังเข้าสู่ระบบ LINE...';sessionStorage.setItem('qcv2_line_login_return','1');liff.login({redirectUri:location.href});return false}if(!(liff.isApiAvailable&&liff.isApiAvailable('shareTargetPicker')))throw new Error('LINE บัญชี/อุปกรณ์นี้ยังไม่รองรับการเปิดรายชื่อผู้รับ');return true}
async function validateImageUrl(url){const r=await fetch(url,{method:'GET',cache:'no-store'});if(!r.ok)throw new Error('ลิงก์รูปเปิดไม่ได้ HTTP '+r.status);const ct=String(r.headers.get('content-type')||'').toLowerCase();if(ct&&!ct.startsWith('image/'))throw new Error('ลิงก์ที่ได้ไม่ใช่ไฟล์รูปภาพ');return true}
async function shareImageToLine(x,c,btn){const oldText=btn?btn.textContent:'';try{if(btn){btn.disabled=true;btn.textContent='กำลังเชื่อมต่อ LINE...'}const ready=await ensureLineReady(btn);if(!ready)return;if(btn)btn.textContent='กำลังเตรียมรูป...';const url=await signed(x.objectPath);if(!url)throw new Error('โหลดลิงก์รูปไม่สำเร็จ');await validateImageUrl(url);const n=c.notice||{},siteName=currentBatch?(currentBatch.site_name||currentBatch.site_code||'-'):'-',workDate=currentBatch?fmtDate(currentBatch.raw_date):'-',batchId=currentBatch&&currentBatch.batch_id?currentBatch.batch_id:'-',coord=hasNotice(c)?fmtCoord(n.actual_latitude)+', '+fmtCoord(n.actual_longitude):'-',mapUrl=hasNotice(c)?'https://www.google.com/maps?q='+encodeURIComponent(n.actual_latitude+','+n.actual_longitude):'',text=['❌ ตรวจงาน QC: รูปไม่ผ่าน','Site: '+siteName,'วันที่งาน: '+workDate,'CA: '+(x.ca||'-'),'ไฟล์: '+(x.name||'-'),'พิกัดใบแจ้งเตือน: '+coord,mapUrl?('แผนที่: '+mapUrl):'','Batch: '+batchId].filter(Boolean).join('\n');if(btn)btn.textContent='เลือกรายชื่อใน LINE...';const result=await liff.shareTargetPicker([{type:'image',originalContentUrl:url,previewImageUrl:url},{type:'text',text}],{isMultiple:true});if(result){if(btn){btn.textContent='ส่งเข้า LINE สำเร็จ ✓';setTimeout(()=>{if(btn&&btn.isConnected)btn.textContent=oldText||'❌ ยืนยันรูปไม่ผ่าน · ส่งเข้า LINE'},1800)}}}catch(e){if(String(e&&e.name||'')==='AbortError')return;alert('แจ้งทาง LINE ไม่สำเร็จ: '+(e&&e.message?e.message:String(e||'')))}finally{if(btn){btn.disabled=false;if(btn.textContent!=='ส่งเข้า LINE สำเร็จ ✓')btn.textContent=oldText||'❌ ยืนยันรูปไม่ผ่าน · ส่งเข้า LINE'}}}

function renderImages(){if(!detailData)return;const imgs=filteredImages(),shown=imgs.slice(0,imageLimit),map=coordMap();if(!shown.length){el('qcv2Images').innerHTML='<div class="qcv2-empty">ไม่พบรายการตามตัวกรองนี้</div>';el('qcv2More').hidden=true;return}el('qcv2Images').innerHTML=shown.map((x,i)=>{const c=map[String(x.ca||'')]||{},n=c.notice||{},ok=hasNotice(c),coord=ok?fmtCoord(n.actual_latitude)+', '+fmtCoord(n.actual_longitude):'-';return `<button class="qcv2-img ${ok?'qcv2-good':'qcv2-missing'}" type="button" data-img="${i}" aria-label="เปิดรายละเอียด CA ${esc(x.ca||'-')}"><div class="qcv2-empty">กำลังโหลดรูป...</div><b>CA ${esc(x.ca||'-')}</b><small>${esc(x.name)}</small><small>พิกัดใบแจ้งเตือน: ${esc(coord)}</small><span class="qcv2-badge">${ok?'มีพิกัด':'ไม่มีพิกัด'}</span></button>`}).join('');shown.forEach((x,i)=>{const box=el('qcv2Images').querySelector('[data-img="'+i+'"]');signed(x.objectPath).then(url=>{if(!box||!box.isConnected)return;const holder=box.firstElementChild;if(url){const im=document.createElement('img');im.loading='lazy';im.src=url;im.alt=x.name;im.dataset.full=url;holder.replaceWith(im)}else holder.textContent='โหลดรูปไม่ได้'})});el('qcv2More').hidden=imgs.length<=imageLimit}

async function openImageDetail(x,c,index,total){ensureModal();const requestId=++modalRequestSeq,n=c.notice||{},ok=hasNotice(c),hasPrev=index>0,hasNext=index<total-1,mapLink=ok?`https://www.google.com/maps?q=${encodeURIComponent(n.actual_latitude+','+n.actual_longitude)}`:'';el('qcv2ModalBody').innerHTML=`<div style="display:flex;align-items:center;justify-content:space-between;gap:10px;padding-right:44px;margin-bottom:12px;flex-wrap:wrap"><strong>รูป ${index+1} / ${total}</strong><div style="display:flex;gap:8px"><button id="qcv2Prev" type="button" ${hasPrev?'':'disabled'}>← ก่อนหน้า</button><button id="qcv2Next" type="button" ${hasNext?'':'disabled'}>ถัดไป →</button></div></div><div class="qcv2-modal-grid"><div id="qcv2ModalImage" class="qcv2-modal-image qcv2-empty">กำลังโหลดรูป...</div><div class="qcv2-modal-info"><h3>CA ${esc(x.ca||'-')}</h3><p><b>ไฟล์:</b> ${esc(x.name)}</p><div class="qcv2-coord"><strong>พิกัดใบแจ้งเตือน</strong><span>${ok?fmtCoord(n.actual_latitude)+', '+fmtCoord(n.actual_longitude):'ไม่มีข้อมูลพิกัด'}</span>${ok?`<a target="_blank" rel="noopener" href="${mapLink}">เปิด Google Maps</a>`:''}</div><div class="qcv2-coord"><strong>พิกัดมิเตอร์</strong><span>พักการใช้งานไว้ก่อน — จะเชื่อมในขั้นถัดไป</span></div><button id="qcv2LineShare" type="button" style="width:100%;margin-top:14px;padding:12px 14px;border:0;border-radius:10px;background:#06c755;color:#fff;font-size:15px;font-weight:800;cursor:pointer">❌ ยืนยันรูปไม่ผ่าน · ส่งเข้า LINE</button></div></div>`;el('qcv2Modal').classList.add('open');const prev=el('qcv2Prev'),next=el('qcv2Next'),lineBtn=el('qcv2LineShare');if(prev)prev.addEventListener('click',()=>moveModal(-1));if(next)next.addEventListener('click',()=>moveModal(1));if(lineBtn)lineBtn.addEventListener('click',()=>shareImageToLine(x,c,lineBtn));const url=await signed(x.objectPath);if(requestId!==modalRequestSeq)return;const holder=el('qcv2ModalImage');if(!holder)return;if(url){const im=document.createElement('img');im.src=url;im.alt=x.name;holder.replaceWith(im)}else holder.textContent='โหลดรูปไม่ได้'}

function boot(){mount();window.addEventListener('divergent:v2-auth',()=>{if(document.body.dataset.auth==='ready')mount()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();