(function(){
'use strict';
const API='https://neauzvqroaszvqffahkv.functions.supabase.co/profit-loss-web-api';
const SESSION_KEY='divergent_web_session_token_v1';
let loadedMonth='';
const money=n=>Number(n||0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
function token(){try{return localStorage.getItem(SESSION_KEY)||''}catch(_){return''}}
function el(id){return document.getElementById(id)}
function currentMonth(){const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function storageKey(month){return 'divergent_v2_pnl_manual_'+month}
function readManual(month){try{return JSON.parse(localStorage.getItem(storageKey(month))||'{}')||{}}catch(_){return{}}}
function writeManual(month,data){try{localStorage.setItem(storageKey(month),JSON.stringify(data))}catch(_){}}
async function api(action,payload={}){const t=token();if(!t)throw new Error('กรุณาเข้าสู่ระบบก่อน');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+t},body:JSON.stringify({action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error==='PROFIT_LOSS_ACCESS_DENIED'?'บัญชีนี้ไม่มีสิทธิ์ดูรายงานกำไร / ขาดทุน':d.error==='SESSION_EXPIRED'?'Session หมดอายุ กรุณาเข้าสู่ระบบใหม่':d.error||('HTTP '+r.status));return d}
function setState(text,error){const s=el('pnlv2State');if(!s)return;s.textContent=text;s.classList.toggle('error',!!error)}
function renderRows(rows){const body=el('pnlv2StaffBody');if(!body)return;if(!rows.length){body.innerHTML='<tr><td colspan="7">ไม่พบข้อมูลเงินเดือนสตาฟในเดือนนี้</td></tr>';return}body.innerHTML=rows.map(r=>'<tr><td>'+(r.employee_name||'-')+'</td><td class="num">'+money(r.base_salary)+'</td><td class="num">'+money(r.social_security)+'</td><td class="num">'+money(r.special_ot)+'</td><td class="num">'+money(r.advance_deduction)+'</td><td class="num">'+money(r.other_deduction)+'</td><td class="num"><strong>'+money(r.net_paid)+'</strong></td></tr>').join('')}
function updateTotals(summary){const month=el('pnlv2Month').value;const manual={revenue:Number(el('pnlv2Revenue').value||0),paper:Number(el('pnlv2Paper').value||0),accounting:Number(el('pnlv2Accounting').value||0),office:Number(el('pnlv2Office').value||0),hospitality:Number(el('pnlv2Hospitality').value||0)};writeManual(month,manual);const employee=Number(summary.employee_payroll_net||0),staff=Number(summary.staff_payroll_net||0),social=Number(summary.staff_social_security||0),expense=Number(summary.staff_expense_total||0);const connected=employee+staff+social+expense;const other=manual.paper+manual.accounting+manual.office+manual.hospitality;const total=connected+other;const profit=manual.revenue-total;el('pnlv2ConnectedCost').textContent=money(connected);el('pnlv2TotalCost').textContent=money(total);el('pnlv2Profit').textContent=(profit<0?'-':'')+money(Math.abs(profit));const pc=el('pnlv2ProfitCard');pc.classList.toggle('bad',profit<0);pc.classList.toggle('good',profit>=0);el('pnlv2Employee').textContent=money(employee);el('pnlv2Staff').textContent=money(staff);el('pnlv2Social').textContent=money(social);el('pnlv2Expense').textContent=money(expense);el('pnlv2EmployeeCount').textContent=Number(summary.employee_payroll_count||0).toLocaleString('th-TH')+' คน';el('pnlv2StaffCount').textContent=Number(summary.staff_count||0).toLocaleString('th-TH')+' คน';el('pnlv2ExpenseCount').textContent=Number(summary.staff_expense_count||0).toLocaleString('th-TH')+' รายการ'}
async function load(){const month=el('pnlv2Month')?.value||currentMonth();setState('กำลังโหลดข้อมูลจริง...',false);try{await api('permissions');const [s,r]=await Promise.all([api('summary',{month}),api('staff_payroll_rows',{month})]);const summary=s.summary||{};loadedMonth=month;const manual=readManual(month);el('pnlv2Revenue').value=Number(manual.revenue||0).toFixed(2);el('pnlv2Paper').value=Number(manual.paper||0).toFixed(2);el('pnlv2Accounting').value=Number(manual.accounting||0).toFixed(2);el('pnlv2Office').value=Number(manual.office||0).toFixed(2);el('pnlv2Hospitality').value=Number(manual.hospitality||0).toFixed(2);renderRows(r.rows||[]);updateTotals(summary);document.querySelector('.workspace[data-workspace="pnl"]').dataset.summary=JSON.stringify(summary);setState('ข้อมูลจริงเชื่อมแล้ว · เดือน '+month,false)}catch(e){setState(e&&e.message?e.message:'โหลดข้อมูลไม่สำเร็จ',true)}}
function bind(){const month=el('pnlv2Month');if(!month)return;month.value=currentMonth();el('pnlv2Reload').addEventListener('click',load);month.addEventListener('change',load);['pnlv2Revenue','pnlv2Paper','pnlv2Accounting','pnlv2Office','pnlv2Hospitality'].forEach(id=>el(id).addEventListener('input',()=>{const ws=document.querySelector('.workspace[data-workspace="pnl"]');let s={};try{s=JSON.parse(ws.dataset.summary||'{}')}catch(_){}updateTotals(s)}));document.querySelectorAll('[data-page="pnl"],[data-open="pnl"]').forEach(x=>x.addEventListener('click',()=>{setTimeout(()=>{if(loadedMonth!==month.value)load();else if(!document.querySelector('.workspace[data-workspace="pnl"]').dataset.summary)load()},0)}));}
function boot(){bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();