from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
MARK='prasat-meter-plan-v1'
if MARK in s:
    print('already patched')
    raise SystemExit

css='''\n<style id="prasat-meter-plan-v1">\n#prasatPlanPage{display:none;max-width:1100px;margin:28px auto;padding:0 20px 80px;font-family:Arial,Tahoma,sans-serif}\n.prasat-plan-head{background:#fff;border-radius:18px;padding:22px;box-shadow:0 4px 18px rgba(0,0,0,.08);margin-bottom:18px}\n.prasat-plan-head h1{margin:0 0 6px;font-size:27px}.prasat-plan-sub{color:#666}.prasat-plan-total{font-size:34px;font-weight:900;color:#6c4ed9;margin-top:14px}.prasat-plan-total small{font-size:15px;color:#666;font-weight:600}\n.prasat-plan-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.prasat-day{background:#fff;border:1px solid #e5e5e5;border-radius:15px;padding:17px;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;box-shadow:0 2px 8px rgba(0,0,0,.04)}.prasat-date{font-size:17px;font-weight:800}.prasat-portion{display:inline-block;margin-top:6px;padding:4px 9px;border-radius:999px;background:#f3f0ff;color:#6c4ed9;font-weight:800}.prasat-count{text-align:right;font-size:29px;font-weight:900;color:#222}.prasat-count small{display:block;font-size:12px;color:#777;font-weight:600}.prasat-back{margin-bottom:14px;background:#555}\n.prasat-plan-menu-card{cursor:pointer}\n@media(max-width:650px){.prasat-plan-grid{grid-template-columns:1fr}.prasat-plan-head h1{font-size:22px}.prasat-plan-total{font-size:30px}}\n</style>\n'''
html='''\n<section id="prasatPlanPage">\n<button class="prasat-back" onclick="closePrasatPlan()">← ย้อนกลับ</button>\n<div class="prasat-plan-head"><h1>แผนการจดหน่วย — กฟส.ปราสาท (M)</h1><div class="prasat-plan-sub">15–24 มิถุนายน 2569 · 10 วัน</div><div class="prasat-plan-total">45,570 <small>รายทั้งหมด</small></div></div>\n<div class="prasat-plan-grid" id="prasatPlanGrid"></div>\n</section>\n'''
js='''\n<script>\n(function(){\n const rows=[['15 มิ.ย. 2569','A1',5079],['16 มิ.ย. 2569','A2',4967],['17 มิ.ย. 2569','A3',4378],['18 มิ.ย. 2569','A4',4344],['19 มิ.ย. 2569','B1',4468],['20 มิ.ย. 2569','B2',4509],['21 มิ.ย. 2569','B3',4366],['22 มิ.ย. 2569','B4',4485],['23 มิ.ย. 2569','C1',4294],['24 มิ.ย. 2569','C2',4680]];\n function render(){const g=document.getElementById('prasatPlanGrid');if(g&&!g.children.length)g.innerHTML=rows.map(r=>`<div class="prasat-day"><div><div class="prasat-date">${r[0]}</div><span class="prasat-portion">${r[1]}</span></div><div class="prasat-count">${r[2].toLocaleString('th-TH')}<small>จำนวนราย</small></div></div>`).join('')}\n window.openPrasatPlan=function(){render();document.querySelectorAll('body > *').forEach(e=>{if(e.id!=='prasatPlanPage'&&e.tagName!=='SCRIPT'&&e.tagName!=='STYLE')e.dataset.prasatPrev=e.style.display,e.style.display='none'});document.getElementById('prasatPlanPage').style.display='block';window.scrollTo(0,0)};\n window.closePrasatPlan=function(){document.getElementById('prasatPlanPage').style.display='none';document.querySelectorAll('[data-prasat-prev]').forEach(e=>{e.style.display=e.dataset.prasatPrev||'';delete e.dataset.prasatPrev})};\n function addMenu(){const candidates=[...document.querySelectorAll('.menu-card,.home-card,.dashboard-card,.card')];const host=candidates.find(x=>/ใบตั้งหนี้|QC|ไซด์งาน|ลูกค้า|พนักงาน/.test(x.textContent||''))?.parentElement;if(!host||document.querySelector('.prasat-plan-menu-card'))return;const d=document.createElement('div');d.className=(candidates[0]?.className||'card')+' prasat-plan-menu-card';d.onclick=openPrasatPlan;d.innerHTML='<div style="font-size:30px;margin-bottom:8px">📅</div><div style="font-weight:900;font-size:17px">แผนการจดหน่วย</div><div style="font-size:13px;color:#666;margin-top:5px">ปราสาท (M) · 45,570 ราย</div>';host.appendChild(d)}\n document.addEventListener('DOMContentLoaded',()=>{render();setTimeout(addMenu,300);setTimeout(addMenu,1500)});\n})();\n</script>\n'''
if '</head>' in s:s=s.replace('</head>',css+'</head>',1)
if '</body>' in s:s=s.replace('</body>',html+js+'</body>',1)
p.write_text(s,encoding='utf-8')
print('patched')
